Monuments
Post-Finem-Team/PostFinem_PreRelease pull request #38
Opened 2023-09-03 16:34 UTC by OK-Diamond

2023-09-03 17:22 UTC, maxice8 requested changes

2023-09-03 17:22 UTC, maxice8 commented on common/great_projects/pf_modified_monuments.txt
> +            custom_tooltip = power_of_ulm
This is not localised

2023-09-03 17:56 UTC, OK-Diamond commented on common/great_projects/pf_modified_monuments.txt
> +            custom_tooltip = power_of_ulm
oops, forgot to remove that
I'll update it and redo the pull req.

2023-09-03 17:57 UTC, maxice8 commented on common/great_projects/pf_modified_monuments.txt
> +            custom_tooltip = power_of_ulm
No need to close, you can just create a new commit and push the same branch, the pull request will keep track of the changes

2023-09-03 18:17 UTC, OK-Diamond commented on common/great_projects/pf_modified_monuments.txt
> +            custom_tooltip = power_of_ulm
Thanks, didn't know this! I've now updated it.

2023-09-04 16:26 UTC, Chewyshoot approved these changes

2023-09-04 16:34 UTC, maxice8 approved these changes

2023-09-04 16:35 UTC, merged