Romuva
Post-Finem-Team/PostFinem_PreRelease pull request #48
Opened 2023-09-10 15:00 UTC by asteraedm

2023-09-10 15:02 UTC, Chewyshoot approved these changes
looks good, cheers to the baltic boiz

2023-09-10 15:02 UTC, Chewyshoot approved these changes
looks good, cheers to the baltic boiz

2023-09-11 03:28 UTC, maxice8 requested changes

2023-09-11 03:28 UTC, maxice8 commented on common/scripted_effects/pf_scripted_effects.txt
> +		remove_church_aspect = bangputys_renewal_aspect
This and the 2 below are using the wrong aspect

2023-09-11 03:28 UTC, maxice8 commented on common/scripted_effects/pf_scripted_effects.txt
> +			has_church_aspect = ausrine_rebirth_aspect
This and the 3 below are using the wrong aspect

2023-09-11 03:28 UTC, maxice8 commented on events/RomuvaEvents.txt
> +# Romuva events
Please name the file `pf_romuva_events` and use the same as namespace

2023-09-15 17:20 UTC, Chewyshoot approved these changes

2023-09-15 17:20 UTC, Chewyshoot approved these changes

2023-09-16 23:44 UTC, maxice8 approved these changes

2023-09-16 23:45 UTC, maxice8 commented
Looks good, just need to solve the conflicts

2023-09-18 22:02 UTC, Chewyshoot approved these changes

2023-09-18 22:02 UTC, Chewyshoot approved these changes

2023-09-18 22:07 UTC, merged