Persia
Post-Finem-Team/PostFinem_PreRelease pull request #66
Opened 2023-10-04 13:01 UTC by SnowLilyx

Persian Mission Tree, Satrapy Demands events (diet-like system), 11 new Satrapies with supporting release events and a mission for the expansion plan. Decision to view expansion plan, a couple new estate privileges and new gov reforms for mission rewards.

2023-10-09 05:27 UTC, maxice8 requested changes
Left some comments with some questions.

2023-10-09 11:28 UTC, SnowLilyx commented on missions/pf_persia.txt
> +			any_subject_country = {
Yes, the mission is "Divide and Conquer", the idea is that once you get one below 50 it becomes easier to do the rest (it's a mission for during the disaster at the start)

2023-10-09 11:28 UTC, SnowLilyx commented on common/ideas/00_country_ideas.txt
> +satrapy_ideas = {
Will move to common/ideas/pf_group_ideas.txt

2023-10-09 11:42 UTC, SnowLilyx commented on missions/pf_persia.txt
> +			custom_tooltip = pf_per_trading_with_faithful_tt
Maybe needs a reword anyway, but you can half and half these (own some and ally the owner of others) so having a :yes: :no: doesn't really make sense? I could change the trigger to be one or the other? Also this def applies to Deal with Gujarat so I'll change it there.

2023-10-09 12:10 UTC, SnowLilyx commented on missions/pf_persia.txt
> +			custom_tooltip = pf_per_trading_with_faithful_tt
Also should I have them for the very first Satrapy Revolt missions? They all say "If we are in the Satrapy Revolt disaster:"

2023-10-11 03:40 UTC, maxice8 requested changes

2023-10-11 03:40 UTC, maxice8 commented on common/peace_treaties/pf_establish_satrapy.txt
> +				change_country_color = { country = ROOT }
Note that the ROOT color here is Persia which has a different color than its satrapies.

Persia is 249 166 2
Satrapies are 255 186 22

2023-10-11 03:40 UTC, maxice8 commented on events/pf_satrapy_events.txt
> +		else_if = {
Since these satrapies are not present at the start of the game, we can have these colors as their starting colors, and add an `effect = { }` in the government reform that sets the country to the satrapy color.

2023-10-11 03:42 UTC, maxice8 commented on events/pf_satrapy_events.txt
> +		else_if = {
I have added the effect, the country colors can be moved, the rationale for why the initial countries were in this event is explained in the comment above the code block, it was a necessity for showing the map properly.

2023-10-11 13:40 UTC, SnowLilyx commented on common/peace_treaties/pf_establish_satrapy.txt
> +				change_country_color = { country = ROOT }
Removed those 2 lines since it's now done in the gov reform

2023-10-11 13:46 UTC, SnowLilyx commented on events/pf_satrapy_events.txt
> +		else_if = {
Change made, you're right doing it in the reform is cleaner

2023-10-15 13:29 UTC, maxice8 requested changes
Made some suggestions on what to use to make events more interactive

2023-10-15 13:29 UTC, maxice8 commented on events/pf_per_events.txt
> +country_event = {
Can't this use `on_conquest`?

2023-10-15 13:29 UTC, maxice8 commented on events/pf_per_events.txt
> +country_event = {
Can't this use the `effect` part of wardeclare diplomatic action?

2023-10-21 14:44 UTC, merged