Monuments
Post-Finem-Team/PostFinem_PreRelease pull request #69
Opened 2023-10-13 16:02 UTC by OK-Diamond

So I got a bit sidetracked...

2023-10-15 13:03 UTC, maxice8 requested changes
Some changes are needed in terms of style and missing province highlighting

2023-10-18 21:15 UTC, OK-Diamond commented on missions/pf_dda_missions.txt
> +                fort_level = 2
Capital forts only provide fort level 1, so they shouldn't count here (as far as I know)

2023-10-18 21:19 UTC, OK-Diamond commented on missions/pf_dda_missions.txt
> +                limit = {any_province = {religion = punic_religion}}
I mistyped this one but the intention was to check in case one of these religions was somehow completely wiped out. I think that a better (and less resource-intensive) way of doing this is by adding some alternate completion method, so I'll get on that.

2023-10-21 14:34 UTC, Chewyshoot approved these changes

2023-10-21 14:36 UTC, merged